# Generated by Django 4.1 on 2022-09-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_student_customuser__college_518644_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['college_id'], name='customuser__college_ee101e_idx'),
        ),
    ]
